### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by ArashDev8** [aXenDeveloper/react-weather#1]
hi
how can I run this file on my linux host?

**Comment by aXenDeveloper** [comment]
Hi,
You have to build app and upload to your server. 
Read more: https://github.com/aXenDeveloper/react-weather#-deployment

**Comment by ArashDev8** [comment]
> Hi, You have to build app and upload to your server. Read more: https://github.com/aXenDeveloper/react-weather#-deployment

thanks to reply but I'm not familiar with building app...!

**Comment by aXenDeveloper** [comment]
Everything is here https://create-react-app.dev/docs/deployment/

**Comment by ArashDev8** [comment]
can you make it as an app and share that?

**Comment by aXenDeveloper** [comment]
It is as an app （︶^︶）

**Comment by ArashDev8** [comment]
> It is as an app （︶^︶）

ok. 
so if I put all file in my host root is it works?

**Comment by aXenDeveloper** [comment]
Please read this: https://create-react-app.dev/docs/deployment/
